server:
  port: 8080

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Ayubjon/sberProject.git
          username: username
          password: password
          default-label: main
          search-paths: "{application}"

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    web:
      exposure:
        include: "*"
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

